[package]
name = "src"
version = "0.1.0"
authors = [
  "NAIBAFFF <fab.andreasson@gmail.com>", 
  "lucubrator <nhopkins@kth.se>",
  "azraneth <azraneth@gmail.com>"
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
